import fs from 'node:fs';

const homePath = 'client/src/pages/Home.tsx';
if (!fs.existsSync(homePath)) process.exit(0);

let source = fs.readFileSync(homePath, 'utf8');

const oldState = `  const [health, setHealth] = useState<any>(null);\n  const [activeTest, setActiveTest] = useState('');\n  const admin = isAdmin();\n  const planned = wakeupDateForEvent(event);`;
const newState = `  const [health, setHealth] = useState<any>(null);\n  const [activeTest, setActiveTest] = useState('');\n  const [scheduleBusy, setScheduleBusy] = useState(false);\n  const [scheduledJobs, setScheduledJobs] = useState<any[]>([]);\n  const admin = isAdmin();\n  const planned = (() => {\n    if (!event || event.placeholder) return null;\n    const base = eventStartDateTime(event);\n    const match = String(event.presentation || '').match(/(\\d{1,2}):(\\d{2})/);\n    if (match) base.setHours(Number(match[1]), Number(match[2]), 0, 0);\n    base.setMinutes(base.getMinutes() - Math.max(20, Number(lead) || 90));\n    return base;\n  })();`;
if (source.includes(oldState)) source = source.replace(oldState, newState);

const oldEffect = `  useEffect(() => {\n    Promise.all([\n      fetch('/api/alarm/health', { cache: 'no-store' }).then((r) => r.json()),\n      getPlatformBilling().catch(() => null),\n    ])\n      .then(([alarm, billing]) => setHealth({ ...(alarm || {}), usage: billing?.usage || null }))\n      .catch(() => setHealth({ ok: false, message: 'Despertador aguardando conexão.' }));\n  }, []);`;
const newEffect = `  async function refreshScheduledJobs() {\n    try {\n      const payload = await authFetch<any>('/api/alarm/scheduled', { cache: 'no-store' });\n      setScheduledJobs(Array.isArray(payload?.jobs) ? payload.jobs : []);\n    } catch {\n      setScheduledJobs([]);\n    }\n  }\n\n  useEffect(() => {\n    Promise.all([\n      fetch('/api/alarm/health', { cache: 'no-store' }).then((r) => r.json()),\n      getPlatformBilling().catch(() => null),\n      refreshScheduledJobs(),\n    ])\n      .then(([alarm, billing]) => setHealth({ ...(alarm || {}), usage: billing?.usage || null }))\n      .catch(() => setHealth({ ok: false, message: 'Despertador aguardando conexão.' }));\n  }, []);`;
if (source.includes(oldEffect)) source = source.replace(oldEffect, newEffect);

const anchor = `  async function testAlarm(testType: 'telegram-message' | 'telegram-call' | 'phone-call') {`;
const scheduleFunctions = `  function serverChannel() {\n    if (channel === 'ligacao') return 'phone-call';\n    if (channel === 'ambos') return 'both';\n    return channel;\n  }\n\n  async function activateServerAlarm() {\n    savePrefs();\n    if (!planned) return toast.info('Importe uma escala com apresentação válida para ativar o despertador.');\n    if (planned.getTime() <= Date.now()) return toast.message('O horário calculado já passou para esta programação.');\n    setScheduleBusy(true);\n    try {\n      const normalizedChannel = serverChannel();\n      const eventKey = [event.id, programDateLabel(event), presentation, lead, normalizedChannel].join(':').replace(/[^a-zA-Z0-9:_-]+/g, '_');\n      const payload = await postCrewCheckJson('/api/alarm/schedule', {\n        scheduledAt: planned.toISOString(),\n        channel: normalizedChannel,\n        chatId,\n        telegramUsername: storage.get('crewcheck_telegram_username', ''),\n        phone: admin ? phone : '',\n        jobKey: 'wakeup:' + eventKey,\n        message: \\`Despertador CrewCheck: hora de se preparar para \\${rosterEventTitle(event)}. Apresentação \\${presentation}. \\${event.origin} → \\${event.destination}.\\`,\n      });\n      if (!payload?.ok) throw new Error(payload?.message || 'Não foi possível agendar.');\n      await refreshScheduledJobs();\n      toast.success(\\`Despertador ativo no servidor para \\${wakeupDateLabel(planned)}.\\`);\n    } catch (error) {\n      toast.error(error instanceof Error ? error.message : 'Não consegui ativar o despertador no servidor.');\n    } finally {\n      setScheduleBusy(false);\n    }\n  }\n\n  async function cancelScheduledJob(job: any) {\n    setScheduleBusy(true);\n    try {\n      const payload = await postCrewCheckJson('/api/alarm/cancel', { id: job.id, jobKey: job.jobKey });\n      if (!payload?.ok) throw new Error(payload?.message || 'Não foi possível cancelar.');\n      await refreshScheduledJobs();\n      toast.success(payload.cancelled ? 'Despertador cancelado.' : 'O despertador já não estava pendente.');\n    } catch (error) {\n      toast.error(error instanceof Error ? error.message : 'Não consegui cancelar o despertador.');\n    } finally {\n      setScheduleBusy(false);\n    }\n  }\n\n`;
if (!source.includes('async function activateServerAlarm()') && source.includes(anchor)) source = source.replace(anchor, scheduleFunctions + anchor);

source = source.replace(`<option value="ligacao">Ligação telefônica Premium</option>`, `<option value="phone-call">Ligação telefônica Premium</option>`);
source = source.replace(`<option value="ambos">Ligação telefônica + Telegram</option>`, `<option value="both">Ligação telefônica + Telegram</option>`);

const oldButtons = `<div className="cz-tool-actions"><button onClick={savePrefs}><Save/> Salvar preferências</button><button onClick={openTelegramBinding}><Send/> Vincular Telegram</button>`;
const newButtons = `<div className="cz-tool-actions"><button className="primary" onClick={activateServerAlarm} disabled={scheduleBusy}><Bell/> {scheduleBusy ? 'Salvando no servidor...' : 'Ativar despertador'}</button><button onClick={savePrefs}><Save/> Salvar preferências</button><button onClick={openTelegramBinding}><Send/> Vincular Telegram</button>`;
if (source.includes(oldButtons)) source = source.replace(oldButtons, newButtons);

const oldTail = `</section><section className="cz-stack-list"><article className="cz-roster-card">`;
const newTail = `</section><section className="cz-toolbox"><h2>Despertadores no servidor</h2><p>Continuam ativos mesmo com o CrewCheck fechado. O servidor verifica a fila automaticamente.</p>{scheduledJobs.length ? <div className="cz-stack-list">{scheduledJobs.slice(0, 12).map((job: any) => <article className="cz-roster-card" key={job.id || job.jobKey}><div className="cz-roster-main"><span className="cz-roster-icon"><Bell/></span><div className="cz-roster-copy"><h3>{wakeupDateLabel(new Date(job.scheduledAt))}</h3><p>{wakeupChannelLabel(job.channel)} · {job.status === 'pending' ? 'Agendado' : job.status === 'sent' ? 'Enviado' : job.status === 'failed' ? 'Falhou' : job.status}</p><small>{job.lastError || (job.sentAt ? \\`Enviado em \\${wakeupDateLabel(new Date(job.sentAt))}\\` : 'Aguardando o horário programado')}</small></div>{job.status === 'pending' && <button onClick={() => cancelScheduledJob(job)} disabled={scheduleBusy}><X/> Cancelar</button>}</div></article>)}</div> : <p className="cz-mini-status">Nenhum despertador gravado no servidor.</p>}</section><section className="cz-stack-list"><article className="cz-roster-card">`;
if (!source.includes('Despertadores no servidor') && source.includes(oldTail)) source = source.replace(oldTail, newTail);

fs.writeFileSync(homePath, source, 'utf8');
console.log('[v1411] Wakeup frontend conectado ao scheduler persistente.');
