import fs from 'node:fs';

const VERSION = '14.3.19';
function update(path, transform, { optional = false } = {}) {
  if (!fs.existsSync(path)) { if (optional) return; throw new Error(`[v14321] Arquivo ausente: ${path}`); }
  const before = fs.readFileSync(path, 'utf8');
  const after = transform(before);
  if (after !== before) fs.writeFileSync(path, after, 'utf8');
}

const css = `/* CrewCheck v14.3.19 — auditoria estrutural com temas próprios e seletores seguros. */
:root{--cc-space-1:4px;--cc-space-2:8px;--cc-space-3:12px;--cc-space-4:16px;--cc-space-5:20px;--cc-space-6:24px;--cc-space-8:32px;--cc-radius-sm:12px;--cc-radius-md:16px;--cc-radius-lg:22px;--cc-radius-xl:28px;--cc-control-h:50px;--cc-content-max:1440px;--cc-nav-safe:calc(108px + env(safe-area-inset-bottom,0px))}
html[data-crewcheck-theme="dark"],html[data-crew-theme="dark"]{--cc-page-bg:#07111f;--cc-page-layer:#0a1728;--cc-card:#102238;--cc-card-alt:#142b45;--cc-card-soft:#0c1d31;--cc-text:#f5f9fd;--cc-heading:#fff;--cc-muted:#b8c8d7;--cc-subtle:#8fa6b9;--cc-border:#294763;--cc-border-strong:#3b617f;--cc-field:#091a2d;--cc-nav:#0c1b2d;--cc-accent:#28c3e9;--cc-accent-soft:rgba(40,195,233,.13);--cc-danger:#fb7185;--cc-warning:#f6bd53;--cc-success:#3dd697;--cc-card-shadow:0 16px 42px rgba(0,0,0,.28)}
html[data-crewcheck-theme="light"],html[data-crew-theme="light"]{--cc-page-bg:#edf4f8;--cc-page-layer:#f7fafc;--cc-card:#fff;--cc-card-alt:#f4f8fb;--cc-card-soft:#f8fbfd;--cc-text:#163047;--cc-heading:#081b2b;--cc-muted:#536d80;--cc-subtle:#748b9d;--cc-border:#c6d5df;--cc-border-strong:#9fb8c8;--cc-field:#fff;--cc-nav:#fff;--cc-accent:#087fac;--cc-accent-soft:rgba(8,127,172,.11);--cc-danger:#b4233d;--cc-warning:#9a5d00;--cc-success:#087f5b;--cc-card-shadow:0 12px 30px rgba(28,66,91,.11)}
@media(prefers-color-scheme:dark){html:not([data-crewcheck-theme="light"]):not([data-crew-theme="light"]){--cc-page-bg:#07111f;--cc-page-layer:#0a1728;--cc-card:#102238;--cc-card-alt:#142b45;--cc-card-soft:#0c1d31;--cc-text:#f5f9fd;--cc-heading:#fff;--cc-muted:#b8c8d7;--cc-subtle:#8fa6b9;--cc-border:#294763;--cc-border-strong:#3b617f;--cc-field:#091a2d;--cc-nav:#0c1b2d;--cc-accent:#28c3e9;--cc-accent-soft:rgba(40,195,233,.13);--cc-card-shadow:0 16px 42px rgba(0,0,0,.28)}}
@media(prefers-color-scheme:light){html:not([data-crewcheck-theme="dark"]):not([data-crew-theme="dark"]){--cc-page-bg:#edf4f8;--cc-page-layer:#f7fafc;--cc-card:#fff;--cc-card-alt:#f4f8fb;--cc-card-soft:#f8fbfd;--cc-text:#163047;--cc-heading:#081b2b;--cc-muted:#536d80;--cc-subtle:#748b9d;--cc-border:#c6d5df;--cc-border-strong:#9fb8c8;--cc-field:#fff;--cc-nav:#fff;--cc-accent:#087fac;--cc-accent-soft:rgba(8,127,172,.11);--cc-card-shadow:0 12px 30px rgba(28,66,91,.11)}}
html,body,#root{min-height:100%;background:var(--cc-page-bg)!important;color:var(--cc-text)!important}body{background-image:linear-gradient(180deg,var(--cc-page-layer),var(--cc-page-bg))!important;overflow-x:hidden}
.cc-main-content,.cc-page,.cc-control-shell,.cc-life-shell,.cc-routine-shell{width:min(100%,var(--cc-content-max));margin-inline:auto;box-sizing:border-box;padding-bottom:var(--cc-nav-safe)}
:is(.cc-card,.cc-control-card,.cc-about-card,.cc-about-founder,.cc-life-day-shell,.cc-routine-daily,.cc-sidebar,.cc-drawer,.cc-premium-card,.cc-metric-card,.cc-alert-card,.cc-roster-card,.cc-routine-card,.cc-departure-card,.cc-radar-card,.cc-hospital-card,.cc-gym-card){background:var(--cc-card)!important;color:var(--cc-text)!important;border:1px solid var(--cc-border)!important;border-radius:var(--cc-radius-lg)!important;box-shadow:var(--cc-card-shadow)!important}
:is(.cc-card,.cc-control-card,.cc-about-card,.cc-about-founder,.cc-life-day-shell,.cc-routine-daily) :is(h1,h2,h3,h4,strong){color:var(--cc-heading)!important}
:is(.cc-card,.cc-control-card,.cc-about-card,.cc-about-founder,.cc-life-day-shell,.cc-routine-daily) :is(p,small){color:var(--cc-muted)!important}
input:not([type="checkbox"]):not([type="radio"]),select,textarea{min-height:var(--cc-control-h);background:var(--cc-field)!important;color:var(--cc-text)!important;border:1px solid var(--cc-border)!important;border-radius:var(--cc-radius-md)!important;padding:12px 14px!important;box-sizing:border-box;box-shadow:none!important}textarea{min-height:96px;resize:vertical}input::placeholder,textarea::placeholder{color:var(--cc-subtle)!important;opacity:1}:is(input,select,textarea):focus{border-color:var(--cc-accent)!important;box-shadow:0 0 0 3px var(--cc-accent-soft)!important;outline:0}
.cc-button-row,.cc-actions,.cc-control-actions,.cc-action-grid,.cc-button-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:var(--cc-space-3)!important;align-items:stretch}.cc-button-row>*,.cc-actions>*,.cc-control-actions>*,.cc-action-grid>*,.cc-button-grid>*{min-height:var(--cc-control-h);width:100%;margin:0!important;box-sizing:border-box}
button:not(.cc-primary):not(.cc-icon-only),a.cc-button,a.cc-btn{background:var(--cc-card-alt)!important;color:var(--cc-text)!important;border:1px solid var(--cc-border)!important;border-radius:var(--cc-radius-md)!important}button:not(.cc-primary):not(.cc-icon-only):hover,a.cc-button:hover,a.cc-btn:hover{background:var(--cc-accent-soft)!important;border-color:var(--cc-accent)!important}
.cc-bottom-nav{background:color-mix(in srgb,var(--cc-nav) 96%,transparent)!important;border:1px solid var(--cc-border)!important;box-shadow:0 -8px 28px color-mix(in srgb,var(--cc-page-bg) 45%,transparent)!important;backdrop-filter:blur(18px)}.cc-bottom-nav-item{color:var(--cc-muted)!important}.cc-bottom-nav-item.active{background:var(--cc-accent-soft)!important;color:var(--cc-accent)!important}.cc-sidebar-nav-item{color:var(--cc-muted)!important}.cc-sidebar-nav-item.active{background:var(--cc-accent-soft)!important;color:var(--cc-accent)!important}
html[data-crewcheck-theme="dark"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero),html[data-crew-theme="dark"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero){background:radial-gradient(circle at 90% 0%,rgba(99,102,241,.21),transparent 38%),linear-gradient(135deg,#102b48,#0b1b31 72%)!important;color:#fff!important;border-color:#315573!important}
html[data-crewcheck-theme="light"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero),html[data-crew-theme="light"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero){background:radial-gradient(circle at 90% 0%,rgba(99,102,241,.10),transparent 38%),linear-gradient(135deg,#fff,#edf7fc 72%)!important;color:var(--cc-text)!important;border-color:var(--cc-border)!important}
html[data-crewcheck-theme="light"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero) :is(h1,h2,h3,strong){color:var(--cc-heading)!important}html[data-crewcheck-theme="light"] :is(.cc-control-hero,.cc-life-ai-hero,.cc-about-hero) :is(p,small){color:var(--cc-muted)!important}
.cc-company-link{display:flex!important;align-items:center!important;gap:10px!important}.cc-company-link::after{content:'Quem somos';margin-left:auto;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--cc-subtle)}
@media(min-width:700px) and (max-width:1180px){.cc-button-row,.cc-actions,.cc-control-actions,.cc-action-grid,.cc-button-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cc-control-form.three{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
@media(max-width:699px){.cc-button-row,.cc-actions,.cc-control-actions,.cc-action-grid,.cc-button-grid{grid-template-columns:1fr}.cc-control-form.two,.cc-control-form.three{grid-template-columns:1fr!important}.cc-company-link::after{display:none}}
`;
fs.writeFileSync('client/src/theme-v14-3-19.css', css, 'utf8');

update('client/src/main.tsx', (source) => source.includes('theme-v14-3-19.css') ? source : source.replace('import "./theme-v14-3-18.css";', 'import "./theme-v14-3-18.css";\nimport "./theme-v14-3-19.css";'));
update('client/src/components/premium/SideDrawer.tsx', (source) => {
  let next = source;
  if (!next.includes('  Building2,')) next = next.replace('  ShieldCheck,\n', '  ShieldCheck,\n  Building2,\n');
  if (!next.includes("view: 'company'")) next = next.replace("      { view: 'support',  label: 'Ajuda',         icon: Mail,     home: true },", "      { view: 'support',  label: 'Ajuda',         icon: Mail,     home: true },\n      { view: 'company',  label: 'CrewCheck',     icon: Building2, href: '/sobre' },");
  next = next.replace('onNavigate: (view: string, home: boolean) => void;', 'onNavigate: (view: string, home: boolean, href?: string) => void;');
  next = next.replace(/onClick=\{\(\) => onNavigate\(item\.view, !!item\.home\)\}/g, "onClick={() => onNavigate(item.view, !!item.home, 'href' in item ? item.href : undefined)}");
  next = next.replace('const handleNav = (view: string, home: boolean) => {\n    if (home)', "const handleNav = (view: string, home: boolean, href?: string) => {\n    if (href) { window.location.assign(href); onClose?.(); return; }\n    if (home)");
  next = next.replace('className={`cc-sidebar-nav-item ${isActive ? \'active\' : \'\'}`}', "className={`cc-sidebar-nav-item ${isActive ? 'active' : ''} ${item.view === 'company' ? 'cc-company-link' : ''}`}");
  return next;
});
update('client/src/pages/AboutUsPage.tsx', (source) => source.replace(/Sobre nós/gi, 'CrewCheck').replace(/Nossa história/g, 'Nossa origem'));
update('client/src/pages/Home.tsx', (source) => source.replace(/const DEFAULT_VERSION = '[^']+';/, `const DEFAULT_VERSION = '${VERSION}';`).replace(/const CREWCHECK_UI_CORE_NOTE = '[^']+';/, `const CREWCHECK_UI_CORE_NOTE = 'v${VERSION}: auditoria estrutural de layout, temas próprios e acesso institucional visível';`), { optional: true });
update('client/src/App.tsx', (source) => source.replace(/crewcheck_last_loaded_version', '[^']+'/g, `crewcheck_last_loaded_version', '${VERSION}'`), { optional: true });
update('client/src/pages/AuthPage.tsx', (source) => source.replace(/crewcheck_last_loaded_version', '[^']+'/g, `crewcheck_last_loaded_version', '${VERSION}'`).replace(/data-version="[^"]+"/g, `data-version="${VERSION}"`), { optional: true });
update('server/platform.mjs', (source) => source.replace(/const APP_VERSION = '\d+\.\d+\.\d+';/, `const APP_VERSION = '${VERSION}';`), { optional: true });
update('server.mjs', (source) => source.replace(/version\s*:\s*'\d+\.\d+\.\d+'/g, `version: '${VERSION}'`).replace(/v=\d+\.\d+\.\d+/g, `v=${VERSION}`).replace(/static-shell-\d+\.\d+\.\d+/g, `static-shell-${VERSION}`), { optional: true });
update('android-wrapper/app/build.gradle', (source) => source.replace(/versionCode\s+\d+/, 'versionCode 140319').replace(/versionName\s+["'][^"']+["']/, `versionName "${VERSION}"`), { optional: true });
update('package.json', (source) => { const data = JSON.parse(source); data.version = VERSION; data.description = `CrewCheck v${VERSION} - structural layout audit, explicit themes and visible company profile`; data.scripts ||= {}; data.scripts['regression:v14.3.19'] = 'node scripts/v139/apply.mjs && node scripts/regression-v14-3-19-layout-structure.mjs'; return `${JSON.stringify(data, null, 2)}\n`; });
console.log(`[v14321] CrewCheck ${VERSION}: auditoria estrutural, temas próprios e CrewCheck no menu.`);
