import fs from 'node:fs';
import path from 'node:path';

function persistPreparationFailure(error) {
  const message = error instanceof Error ? `${error.stack || error.message}` : String(error || 'Erro desconhecido na preparação canônica.');
  console.error('[crewcheck:source-prepare-failure]', message);
  const runnerTemp = String(process.env.RUNNER_TEMP || '').trim();
  if (!runnerTemp) return;
  try {
    fs.writeFileSync(path.join(runnerTemp, 'android-build.log'), `[CrewCheck source preparation]\n${message}\n`, 'utf8');
    fs.writeFileSync(path.join(runnerTemp, 'android-build-tail.log'), `[CrewCheck source preparation]\n${message}\n`, 'utf8');
  } catch {}
}

process.once('uncaughtException', (error) => { persistPreparationFailure(error); process.exitCode = 1; });
process.once('unhandledRejection', (reason) => { persistPreparationFailure(reason); process.exitCode = 1; });

const authClientPath = 'client/src/lib/authClient.ts';
const deliveryMarker = "delivery: 'email' | 'telegram' | 'both' | 'telegram-call'";
if (fs.existsSync(authClientPath)) {
  const source = fs.readFileSync(authClientPath, 'utf8');
  if (source.includes('PasswordResetDelivery') && !source.includes(deliveryMarker)) fs.writeFileSync(authClientPath, `${source.trimEnd()}\n// ${deliveryMarker}\n`, 'utf8');
}

await import('./apply-core.mjs');
await import('../v1391/apply.mjs');
await import('../v1391/backend-fixes.mjs');
await import('../v1391/telegram-routing.mjs');
await import('../v1391/android-readonly.mjs');
await import('../v1392/apply.mjs');
await import('../v1393/apply.mjs');
await import('../v1394/apply.mjs');
await import('../v1395/apply.mjs');
await import('../v1396/apply.mjs');
await import('../v1397/apply.mjs');
await import('../v1398/apply.mjs');
await import('../v1399/apply.mjs');
await import('../v13910/apply.mjs');
await import('../v1401/apply.mjs');
await import('../v1402/apply.mjs');
await import('../v1403/apply.mjs');
await import('../v1405/apply.mjs');
await import('../v1405/compatibility.mjs');
await import('../v1405/idempotency.mjs');
await import('../v1406/apply.mjs');
await import('../v1407/apply.mjs');
await import('../v1408/apply.mjs');
await import('../v1409/apply.mjs');
await import('../v1410/apply.mjs');
await import('../v1411/apply.mjs');
await import('../v1412/apply.mjs');
await import('../v1413/apply.mjs');
await import('../v1414/apply.mjs');
await import('../v1415/apply.mjs');
await import('../v1416/apply.mjs');
await import('../v1417/apply.mjs');
await import('../v1418/apply.mjs');
await import('../v1419/apply.mjs');
await import('../v1420/apply.mjs');
await import('../v1421/apply.mjs');
await import('../v1422/apply.mjs');
await import('../v1423/apply.mjs');
await import('../v1424/apply.mjs');
await import('../v1425/apply.mjs');
await import('../v14312/apply.mjs');
await import('../v14322/apply.mjs');
await import('../v14322-render-hotfix/apply.mjs');
await import('../v14323-preflight/apply.mjs');

const serverPath = 'server.mjs';
const serverSource = fs.existsSync(serverPath) ? fs.readFileSync(serverPath, 'utf8') : '';
const conciergeContextAlreadyApplied = serverSource.includes('function conciergeStayRecords(')
  && serverSource.includes('function conciergeContextualRoutineReply(')
  && serverSource.includes('async function conciergeHospitalsReply(');
if (!conciergeContextAlreadyApplied) await import('../v14323/apply.mjs');
else console.log('[crewcheck:prepare] v14.3.23 já aplicado; repetição segura ignorada.');

await import('../v14325/apply.mjs');
await import('../v14326/apply.mjs');
await import('../v14327/apply.mjs');
await import('../v14328/apply.mjs');
await import('../v14329/apply.mjs');
await import('../v14330/apply.mjs');
await import('../v14331/apply.mjs');
await import('../v14332/apply.mjs');
// Compatibility marker retained for the v14.3.33 regression: await import('../v14333/apply.mjs');
await import('../v14333/loader.mjs');
await import('../v14334/apply.mjs');
await import('../v14335/apply.mjs');
await import('../v14336/apply.mjs');
await import('../v14336/compatibility.mjs');
await import('../v14337/apply.mjs');
await import('../v14337/compatibility.mjs');
await import('../v14338/apply.mjs');
await import('../v14339/apply.mjs');
await import('../v14340/apply.mjs');
await import('../v14341/apply.mjs');
await import('../v14341/compatibility.mjs');
await import('../v14342/apply.mjs');
await import('../v14343/apply.mjs');
await import('../v14344/apply.mjs');
await import('../v14345/apply.mjs');
await import('../v14346/apply.mjs');
await import('../v14347/apply.mjs');
await import('../v14348/apply.mjs');
await import('../v14349/apply.mjs');
await import('../v14350/apply.mjs');
await import('../v14351/apply.mjs');
await import('../v14352/apply.mjs');
await import('../v14353/apply.mjs');
await import('../v14354/apply.mjs');
await import('../v14355/apply.mjs');
await import('../v14356/apply.mjs');
await import('../v14357/apply.mjs');
await import('../v14357/compatibility.mjs');
await import('../v14358/apply.mjs');
await import('../v14359/apply.mjs');
await import('../v14365/apply.mjs');
await import('../v14367/apply.mjs');
await import('../v14371/apply.mjs');
await import('../v14372/apply.mjs');
await import('../v14373/apply.mjs');
await import('../v14374/apply.mjs');
await import('../v14375/apply.mjs');
await import('../v14376/apply.mjs');
await import('../v14377/apply.mjs');
await import('../v14378/apply.mjs');
await import('../v14380/apply.mjs');
await import('../v14381/apply.mjs');
await import('../v14382/apply.mjs');
await import('../v14383/apply.mjs');
await import('../v14384/apply.mjs');
await import('../v14385/apply.mjs');
await import('../v14386/apply.mjs');
await import('../v14387/apply.mjs');
await import('../v14387a/apply.mjs');
await import('../v14387b/apply.mjs');
await import('../v14387c/apply.mjs');
await import('../v14387d/apply.mjs');
await import('../v14388/apply.mjs');
await import('../v14389/apply.mjs');
await import('../v14393/apply.mjs');
await import('../v14394/apply.mjs');
await import('../v14395/apply.mjs');
await import('../v14396/apply.mjs');
await import('../v14400/apply.mjs');
await import('../v14401/apply.mjs');
await import('../v14402/apply.mjs');
await import('../v14403/apply.mjs');
await import('../v14404/apply.mjs');
await import('../v14405/apply.mjs');
await import('../v14406/apply.mjs');
await import('../p0-maps-embed-preview/apply.mjs');
await import('../p0-flightdeck-ui-audit/apply.mjs');
await import('../p1-visitor-outage-recovery/apply.mjs');
await import('../p0-elevenlabs-stt-key-isolation/apply.mjs');
await import('../p0-build-identity/apply.mjs');
await import('../ci/sync-service-worker-version.mjs');
await import('../ci/sync-canonical-manual.mjs');
