import fs from 'node:fs';

// Terminal, isolated overlay: the base Home and Android bridge are generated by
// the existing preparation chain. Never materialize its unrelated P0 changes.
function update(path, transform) {
  const before = fs.readFileSync(path, 'utf8');
  const after = transform(before);
  if (after !== before) fs.writeFileSync(path, after);
}
function replace(source, before, after) {
  if (source.includes(after)) return source;
  if (!source.includes(before)) throw new Error(`[P1 PDF Intake] Missing anchor: ${before.slice(0, 90)}`);
  return source.replace(before, after);
}

update('client/src/pages/Home.tsx', (source) => {
  const marker = "import { PdfIntakeQueue, decodeSharedPdf } from '@/lib/universalPdfIntake';";
  if (!source.includes(marker)) {
    source = replace(source, "import CrewLockerView from '@/components/v1435/CrewLockerView';", `import CrewLockerView from '@/components/v1435/CrewLockerView';
${marker}
import { inspectIntakePdf } from '@/lib/inspectIntakePdf';
import UniversalPdfChoice from '@/components/UniversalPdfChoice';
import '@/components/universal-pdf-intake.css';`);
    const start = source.indexOf('  const nativePdfClaimsRef = useRef<Set<string>>(new Set());');
    const end = source.indexOf('  }, [bundle]);', start);
    if (start < 0 || end < 0) throw new Error('[P1 PDF Intake] Existing native PDF bridge missing');
    source = source.slice(0, start) + fs.readFileSync(new URL('./home-bridge.txt', import.meta.url), 'utf8')
      + source.slice(end + '  }, [bundle]);'.length);
  }
  source = replace(source, "{view === 'crewlocker' && <CrewLockerView/>}", "{view === 'crewlocker' && <CrewLockerView incoming={walletImport || undefined} onIncomingDone={() => walletImport?.finish()}/>}");
  source = replace(source, "    {view === 'cockpit' && <Cockpit", `    {pdfChoice && <UniversalPdfChoice file={pdfChoice.file} onChoose={pdfChoice.finish}/>}
    {(view === 'cockpit' || (walletImport && view !== 'crewlocker')) && <button className="cc-wallet-quick" onClick={() => setView('crewlocker')}>Crew Wallet{walletImport ? ' — PDF aguardando revisão' : ''}</button>}
    {view === 'cockpit' && <Cockpit`);
  return source;
});

update('android-wrapper/app/src/main/AndroidManifest.xml', (source) => {
  source = replace(source, 'android:name=".MainActivity"\n', 'android:name=".MainActivity"\n            android:launchMode="singleTop"\n');
  // EXTRA_STREAM is not Intent.data: retain compatibility filters and add the
  // standard MIME-only SEND filter, for share sheets supplying no data URI.
  return replace(source, '            <intent-filter>\n                <action android:name="android.intent.action.MAIN"', `            <!-- Universal PDF Intake: EXTRA_STREAM / ClipData, without Intent.data -->
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/pdf" />
                <data android:mimeType="application/octet-stream" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"`);
});

console.log('[P1 PDF Intake] Existing bridge routes to roster confirmation or encrypted wallet.');
