import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compiled = ts.transpileModule(fs.readFileSync('scripts/crewlife-wellness/wellness.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { normalizeWellness, manualWellness, suggestWellness, metricText } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const now = Date.parse('2026-09-22T15:00:00Z');
const observation = (value, source = 'samsung-health', date = now - 3600000) => ({ value, source, observedAt: new Date(date).toISOString() });
assert.deepEqual(normalizeWellness(null, 'samsung-health', now), {});
for (const value of [null, undefined, '100', NaN, Infinity, -1, 200001, 1.5]) assert.deepEqual(normalizeWellness({ steps: observation(value) }, 'samsung-health', now), {});
for (const date of [now + 1, now - 86400000]) assert.deepEqual(normalizeWellness({ steps: observation(200, 'samsung-health', date) }, 'samsung-health', now), {});
assert.equal(normalizeWellness({ steps: observation(0) }, 'samsung-health', now).steps.value, 0);
assert.deepEqual(normalizeWellness({ energyScore: observation(90, 'manual') }, 'manual', now), {});
assert.deepEqual(normalizeWellness({ steps: observation(200, 'manual') }, 'samsung-health', now), {});
assert.deepEqual(manualWellness({sleepHours:0,steps:0,activityMinutes:0,updatedAt:new Date(now).toISOString()}, now), {});
const slept = { sleepMinutes: observation(480), energyScore: observation(100), sleepScore: observation(100) };
assert.equal(suggestWellness(slept, 'unwell', 8, now).kind, 'rest');
assert.equal(suggestWellness(slept, 'tired', 8, now).kind, 'rest');
assert.equal(suggestWellness(slept, 'unknown', 8, now).kind, 'check-in');
assert.equal(suggestWellness({}, 'well', 8, now).kind, 'check-in');
assert.equal(suggestWellness({ sleepMinutes: observation(300) }, 'well', 8, now).kind, 'gentle');
assert.equal(suggestWellness(slept, 'well', 8, now).kind, 'choice');
assert.equal(suggestWellness(slept, 'well', 8, now + 86400000).kind, 'check-in');
assert.equal(metricText('steps'), 'Sem dado');
assert.equal(metricText('sleepMinutes', observation(480)), '8h 00min');
const ui = fs.readFileSync('scripts/crewlife-wellness/WellnessDashboard.tsx', 'utf8');
assert(!/localStorage|sessionStorage|fetch\(|sendBeacon/.test(ui), 'Samsung observations must remain session memory only');
const native = fs.readFileSync('android-wrapper/app/src/main/java/com/crewcheck/app/MainActivity.java', 'utf8');
assert(!native.includes('getSamsungWellnessStatus'), 'This draft must not expose an unapproved Samsung integration');
console.log('CrewLife wellness: malformed data, freshness, provenance, zero semantics, conservative suggestions and isolation passed.');
