export default function AboutUsPage() {
  const features = ['Escala operacional','Saída Inteligente','Radar de voos','Meteorologia aeronáutica','Alertas operacionais','Regulamentação','Concierge Operacional','Integrações com Telegram e calendário'];
  return <main className="cc-about">
    <section className="cc-about-hero">
      <a className="cc-about-brand" href="/">✈ <strong>CrewCheck</strong></a>
      <span>Bruno Medeiros Tecnologia</span>
      <h1>Inteligência operacional para profissionais da aviação.</h1>
      <p>Transformamos a complexidade da rotina operacional em informações claras, decisões mais seguras e mais tranquilidade para quem trabalha voando.</p>
      <div><a className="primary" href="/login">Acessar o CrewCheck</a><a href="mailto:bruno@crewcheck.online?subject=Demonstração%20CrewCheck">Solicitar demonstração</a></div>
    </section>
    <section className="cc-about-content">
      <article><span>Nossa história</span><h2>Criado a partir da experiência real na aviação</h2><p>O CrewCheck nasceu para reunir, em um único lugar, informações que normalmente ficam espalhadas entre escalas, documentos, aplicativos e sistemas operacionais. Mais do que organizar uma escala, a plataforma ajuda o profissional a compreender sua programação, planejar deslocamentos e acompanhar informações relevantes para sua rotina.</p></article>
      <div className="cc-about-duo"><article><span>Missão</span><h2>Simplificar a rotina operacional</h2><p>Tornar a rotina dos profissionais da aviação mais simples, organizada e segura por meio de tecnologia acessível e inteligência operacional.</p></article><article><span>Visão</span><h2>Ser referência no setor</h2><p>Ser uma plataforma de referência em inteligência operacional para profissionais da aviação.</p></article></div>
      <section><span>O que fazemos</span><h2>Toda a sua rotina operacional. Em uma única plataforma.</h2><div className="cc-about-features">{features.map((item)=><div key={item}>✓ {item}</div>)}</div></section>
      <article className="cc-about-founder"><span>Fundador</span><h2>Bruno Saraiva de Medeiros</h2><strong>Founder & CEO</strong><p>Profissional da aviação e fundador da Bruno Medeiros Tecnologia. O CrewCheck foi desenvolvido a partir da experiência prática com escalas, jornadas, deslocamentos e desafios da rotina operacional.</p></article>
      <article className="cc-about-note"><h2>Independência e transparência</h2><p>O CrewCheck é uma plataforma independente. Não representa nem substitui companhias aéreas, autoridades aeronáuticas ou sistemas oficiais. Informações operacionais devem ser confirmadas nos canais oficiais aplicáveis.</p></article>
    </section>
    <style>{`.cc-about{min-height:100vh;background:linear-gradient(145deg,#071426,#0c2342 55%,#151331);color:#fff;font-family:Inter,system-ui,sans-serif}.cc-about-hero,.cc-about-content{max-width:1120px;margin:auto;padding:clamp(28px,7vw,84px) clamp(20px,5vw,52px)}.cc-about-brand{display:inline-flex;gap:10px;align-items:center;color:#fff;text-decoration:none;font-size:28px}.cc-about-hero>span,.cc-about-content span{display:block;margin-top:30px;color:#f44ab5;font-weight:800;letter-spacing:.12em;text-transform:uppercase;font-size:12px}.cc-about h1{max-width:850px;font-size:clamp(38px,7vw,78px);line-height:1.02;margin:20px 0}.cc-about-hero p{max-width:760px;font-size:clamp(18px,2.3vw,24px);line-height:1.55;color:#cfdaeb}.cc-about-hero div{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.cc-about a{border:1px solid #42c7ff;border-radius:14px;padding:13px 18px;color:#fff;text-decoration:none;font-weight:800}.cc-about a.primary{border:0;background:linear-gradient(90deg,#f437a7,#4dcfff)}.cc-about-content{display:grid;gap:24px;padding-top:0}.cc-about article,.cc-about-content>section{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.13);border-radius:24px;padding:clamp(22px,4vw,38px);backdrop-filter:blur(12px)}.cc-about h2{font-size:clamp(24px,4vw,38px);margin:10px 0 14px}.cc-about article p,.cc-about-content section p{color:#c7d3e5;line-height:1.7}.cc-about-duo{display:grid;grid-template-columns:1fr 1fr;gap:24px}.cc-about-features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:22px}.cc-about-features div{background:rgba(4,13,29,.5);border-radius:14px;padding:15px}.cc-about-founder strong{color:#4dcfff}.cc-about-note{border-color:rgba(244,74,181,.35)!important}@media(max-width:720px){.cc-about-duo,.cc-about-features{grid-template-columns:1fr}}`}</style>
  </main>;
}
