import fs from 'node:fs';
const path = 'client/src/pages/Home.tsx';
let source = fs.readFileSync(path, 'utf8');
if (!source.includes('// departure-location-consistency')) {
  const edit = (before, after) => {
    if (!source.includes(before)) throw Error(`Departure location marker missing: ${before.slice(0, 80)}`);
    source = source.replace(before, after);
  };
  edit("const CURRENT_GEO_MAX_AGE_MS = 30 * 60_000;", "// departure-location-consistency\nconst CURRENT_GEO_MAX_AGE_MS = 75_000;");
  edit("  capturedAt: string;\n  source:", "  capturedAt: string;\n  accountId?: string | number | null;\n  source:");
  edit("    capturedAt,\n    source: position.source,", "    capturedAt,\n    accountId: getStoredUser()?.id,\n    source: position.source,");
  edit("  if (!pair || !samePoint || !fresh) {", "  if (!pair || !samePoint || !fresh || meta?.accountId !== getStoredUser()?.id || !Number.isFinite(Number(meta?.accuracy)) || Number(meta?.accuracy) <= 0 || Number(meta?.accuracy) > 180) {");
  // Preserve the device observation time. Old native fallback fixes must not be
  // promoted to fresh observations when their callback arrives.
  source = source.replaceAll("Promise<{ lat: number; lng: number; accuracy?: number }>", "Promise<{ lat: number; lng: number; accuracy?: number; capturedAt?: string }>");
  edit("      resolve({ ...point, accuracy: Number.isFinite(Number(detail.accuracy)) ? Number(detail.accuracy) : undefined });", "      const observedAt = Number(detail.time);\n      const accuracy = Number(detail.accuracy);\n      if (!Number.isFinite(observedAt) || Date.now() - observedAt < 0 || Date.now() - observedAt > CURRENT_GEO_MAX_AGE_MS || !Number.isFinite(accuracy) || accuracy <= 0 || accuracy > 180) { reject(new Error('Localização antiga ou sem precisão suficiente. Atualize o GPS.')); return; }\n      resolve({ ...point, accuracy, capturedAt: new Date(observedAt).toISOString() });");
  edit("        resolve({\n          ...point,\n          accuracy:", "        const observedAt = Number(position.timestamp);\n        const accuracy = Number(position.coords.accuracy);\n        if (!Number.isFinite(observedAt) || Date.now() - observedAt < 0 || Date.now() - observedAt > CURRENT_GEO_MAX_AGE_MS || !Number.isFinite(accuracy) || accuracy <= 0 || accuracy > 180) { reject(new Error('Localização antiga ou sem precisão suficiente. Atualize o GPS.')); return; }\n        resolve({\n          ...point,\n          capturedAt: new Date(observedAt).toISOString(),\n          accuracy:");
  edit("  let position: { lat: number; lng: number; accuracy?: number } | null", "  const accountId = getStoredUser()?.id;\n  let position: { lat: number; lng: number; accuracy?: number; capturedAt?: string } | null");
  edit("  const saved = persistCurrentGeoPosition({ ...position, source });", "  if (accountId !== getStoredUser()?.id) throw new Error('A conta mudou durante a localização.');\n  const saved = persistCurrentGeoPosition({ ...position, source });");
  edit("    return storage.get('crewcheck_last_geo', '');\n  }\n}\n\nfunction eventRouteOrigin", "    const saved = loadFreshCurrentGeo();\n    return saved ? coordsLabel(saved.lat, saved.lng) : '';\n  }\n}\n\nfunction eventRouteOrigin");
  edit("  return 'Minha localização';\n}\nfunction eventRouteOriginLabel", "  return '';\n}\nfunction eventRouteOriginLabel");
  edit("  if (!coordinatePair(origin)) return origin;", "  if (!coordinatePair(origin)) return origin || 'Localização indisponível ou desatualizada';");
  edit("  const cached = loadNearbyAddress(origin)?.coordinates;", "  const cached = coordinatePair(origin) ? loadNearbyAddress(origin)?.coordinates : null;");
  edit("origin = eventRouteOrigin(event)): DeparturePositioningPlan", "origin = route?.clientOrigin ?? eventRouteOrigin(event)): DeparturePositioningPlan");
  edit("  const hasValidRouteDistance = Number.isFinite(routeDistanceMeters) && routeDistanceMeters > 0;", "  const hasValidRouteDistance = Boolean(origin) && route?.ok === true && route?.clientRouteState !== 'stale' && route?.clientRouteState !== 'pending' && Number.isFinite(routeDistanceMeters) && routeDistanceMeters > 0;");
  edit("  const routeAccountId = getStoredUser()?.id || null;", "  const routeAccountId = getStoredUser()?.id || null;\n  const locationRequestRef = useRef(0);\n  useEffect(() => {\n    ++locationRequestRef.current;\n    setOrigin(eventRouteOrigin(event));\n    setRoute(null);\n    onRoute?.(null);\n    const resume = () => {\n      ++locationRequestRef.current;\n      setOrigin(eventRouteOrigin(event));\n      setLocationRevision(value => value + 1);\n      void getCurrentGeoPosition().catch(() => undefined);\n    };\n    window.addEventListener('focus', resume);\n    const timer = window.setInterval(() => { if (!storage.get('crewcheck_manual_route_origin', '') && !loadFreshCurrentGeo()) resume(); }, 15_000);\n    return () => { ++locationRequestRef.current; window.removeEventListener('focus', resume); window.clearInterval(timer); };\n  }, [event.id, event.origin, event.destination, event.hotel, routeAccountId]);");
  edit("      const direct = detail.coordinates || null;", "      const direct = loadFreshCurrentGeo();");
  edit("      setRoute(info);\n      onRoute?.(info);", "      const observation = { ...info, clientOrigin: origin };\n      setRoute(observation);\n      onRoute?.(observation);");
  edit("      void fetchRoutePreviewInfo(origin, destination, mapsMode).then((info) => session.complete(request, info));", "      if (!origin) { session.complete(request, { ok: false, message: 'Localização indisponível ou desatualizada. Atualize a localização ou informe uma origem manual.' }); return; }\n      void fetchRoutePreviewInfo(origin, destination, mapsMode).then((info) => session.complete(request, info));");
  edit("  async function refreshLocation() {\n    try {", "  async function refreshLocation() {\n    const request = ++locationRequestRef.current;\n    try {");
  edit("      const position = await getCurrentGeoPosition();\n      const next = coordsLabel(position.lat, position.lng);", "      const position = await getCurrentGeoPosition();\n      if (request !== locationRequestRef.current) return;\n      storage.set('crewcheck_manual_route_origin', '');\n      const next = coordsLabel(position.lat, position.lng);");
  edit("      const address = await reverseGeocodePosition(position.lat, position.lng);\n      const label", "      const address = await reverseGeocodePosition(position.lat, position.lng);\n      if (request !== locationRequestRef.current) return;\n      const label");
  edit("    } catch (error) {\n      toast.error(error instanceof Error ? error.message : 'Não consegui atualizar sua localização.');", "    } catch (error) {\n      if (request !== locationRequestRef.current) return;\n      setOrigin('');\n      setOriginLabel('Localização indisponível ou desatualizada');\n      onOriginLabel?.('Localização indisponível ou desatualizada');\n      toast.error(error instanceof Error ? error.message : 'Não consegui atualizar sua localização.');");
  edit("if (manual.trim()) { storage.set('crewcheck_manual_route_origin'", "if (manual.trim()) { ++locationRequestRef.current; storage.set('crewcheck_manual_route_origin'");
  // Do not label the presentation airport as the local positioning airport:
  // this preview remains the observed route to the presentation airport.
  edit("positioningPlan.requiresFlight ? safe(positioningPlan.originAirport?.code, 'Aeroporto local') : safe(event.origin || event.destination, 'Aeroporto')", "safe(event.origin || event.destination, 'Aeroporto')");
  edit("  const travelMinutes = transitPresentation ? transitMinutes : liveMinutes || cachedMinutes || defaultDepartureTravelMinutes();", "  const locationMissing = !(route?.clientOrigin ?? eventRouteOrigin(event));\n  const travelMinutes = transitPresentation ? transitMinutes : liveMinutes || cachedMinutes || defaultDepartureTravelMinutes();");
  edit("    leaveLabel: transitPresentation && !transitPresentation.showDepartureTime ? 'A confirmar'", "    leaveLabel: locationMissing ? 'A confirmar' : transitPresentation && !transitPresentation.showDepartureTime ? 'A confirmar'");
  edit("type RoutePreviewInfo = {", "type RoutePreviewInfo = {\n  clientOrigin?: string;");
  edit("  const saved = persistCurrentGeoPosition({ ...position, source });", "  const saved = persistCurrentGeoPosition({ ...position, source });\n  window.dispatchEvent(new CustomEvent('crewcheck:location-updated', { detail: { coordinates: saved } }));");
  edit("  const capturedAt = position.capturedAt || new Date().toISOString();", "  const capturedAt = position.capturedAt || new Date().toISOString();\n  let previous: Partial<CrewFreshGeoPosition> | null = null;\n  try { previous = JSON.parse(storage.get(CURRENT_GEO_META_KEY, 'null')); } catch {}\n  if (previous?.accountId === getStoredUser()?.id && Date.parse(String(previous?.capturedAt || '')) > Date.parse(capturedAt)) throw new Error('Resposta de localização anterior à última captura.');");
  edit("      const detail = (incoming as CustomEvent).detail || {};\n      const direct = loadFreshCurrentGeo();", "      const detail = (incoming as CustomEvent).detail || {};\n      if (storage.get('crewcheck_manual_route_origin', '')) return;\n      const direct = loadFreshCurrentGeo();");
  edit("  const latitude = Number(lat);", "  if (lat == null || lng == null || lat === '' || lng === '') return null;\n  const latitude = Number(lat);");
  edit("  }, [event.id, origin, destination, mapsMode, routeAccountId]);", "  }, [event.id, event.origin, event.presentation, event.departure, origin, destination, mapsMode, routeAccountId]);");
  edit("return `crewcheck_positioning_flight:${event.id}`;", "return `crewcheck_positioning_flight:${getStoredUser()?.id || 'anonymous'}:${event.id}:${event.origin}:${event.presentation}:${eventRouteOrigin(event)}`;");
  edit("return `crewcheck_positioning_search:${event.id}`;", "return `crewcheck_positioning_search:${getStoredUser()?.id || 'anonymous'}:${event.id}:${event.origin}:${event.presentation}:${eventRouteOrigin(event)}`;");
  source = source.replaceAll("storage.get('crewcheck_manual_route_origin', '')", "(storage.get('crewcheck_manual_route_account', '') === String(getStoredUser()?.id || '') ? storage.get('crewcheck_manual_route_origin', '') : '')");
  edit("storage.set('crewcheck_manual_route_origin', manual.trim());", "storage.set('crewcheck_manual_route_origin', manual.trim()); storage.set('crewcheck_manual_route_account', String(getStoredUser()?.id || ''));");
  fs.writeFileSync(path, source);
}
